/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.validation

import org.eclipse.xtext.validation.Check
import dk.sdu.mmmi.mdsd.math.MathExp
import dk.sdu.mmmi.mdsd.math.MathPackage
import dk.sdu.mmmi.mdsd.math.Origen

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class MathValidator extends AbstractMathValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					MathPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	
	
	@Check
	def checkMathStuff(MathExp exp){
		var valNames = (exp.eContainer as Origen).x.map[ name ].toList()
		var tempList = valNames.filter[it == exp.name]
		if (valNames.filter[it == exp.name].length > 1) {
			error("Variable is in use",MathPackage.Literals.LET__VAL, 'invalidName')
		}
	
	}
}
