/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.scoping;

import com.google.common.base.Objects;
import dk.sdu.mmmi.mdsd.math.Let;
import dk.sdu.mmmi.mdsd.math.MathExp;
import dk.sdu.mmmi.mdsd.math.MathPackage;
import dk.sdu.mmmi.mdsd.math.Origen;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MathScopeProvider extends AbstractMathScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    boolean _equals = Objects.equal(reference, MathPackage.Literals.VARIABLE_USE__REF);
    if (_equals) {
      return this.getherVariables(context);
    }
    return super.getScope(context, reference);
  }
  
  protected IScope getherVariables(final EObject context) {
    IScope _switchResult = null;
    EObject _eContainer = context.eContainer();
    boolean _matched = false;
    if (_eContainer instanceof Let) {
      _matched=true;
      _switchResult = Scopes.scopeFor(CollectionLiterals.<EObject>newArrayList(context.eContainer()), this.getherVariables(context.eContainer()));
    }
    if (!_matched) {
      if (_eContainer instanceof Origen) {
        _matched=true;
        EObject _eContainer_1 = context.eContainer();
        final Function1<MathExp, Boolean> _function = (MathExp it) -> {
          return Boolean.valueOf((!Objects.equal(it, context)));
        };
        _switchResult = Scopes.scopeFor(IterableExtensions.<MathExp>filter(((Origen) _eContainer_1).getX(), _function));
      }
    }
    if (!_matched) {
      _switchResult = this.getherVariables(context.eContainer());
    }
    return _switchResult;
  }
}
