/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.mdsd.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.mmmi.mdsd.ide.contentassist.antlr.internal.InternalMathParser;
import dk.sdu.mmmi.mdsd.services.MathGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class MathParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(MathGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, MathGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getExp1Access().getAlternatives_1(), "rule__Exp1__Alternatives_1");
			builder.put(grammarAccess.getExp2Access().getAlternatives_1(), "rule__Exp2__Alternatives_1");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getMathAccess().getAlternatives(), "rule__Math__Alternatives");
			builder.put(grammarAccess.getMathExpAccess().getGroup(), "rule__MathExp__Group__0");
			builder.put(grammarAccess.getExp1Access().getGroup(), "rule__Exp1__Group__0");
			builder.put(grammarAccess.getExp1Access().getGroup_1_0(), "rule__Exp1__Group_1_0__0");
			builder.put(grammarAccess.getExp1Access().getGroup_1_1(), "rule__Exp1__Group_1_1__0");
			builder.put(grammarAccess.getExp2Access().getGroup(), "rule__Exp2__Group__0");
			builder.put(grammarAccess.getExp2Access().getGroup_1_0(), "rule__Exp2__Group_1_0__0");
			builder.put(grammarAccess.getExp2Access().getGroup_1_1(), "rule__Exp2__Group_1_1__0");
			builder.put(grammarAccess.getParenthesisAccess().getGroup(), "rule__Parenthesis__Group__0");
			builder.put(grammarAccess.getLetAccess().getGroup(), "rule__Let__Group__0");
			builder.put(grammarAccess.getOrigenAccess().getXAssignment(), "rule__Origen__XAssignment");
			builder.put(grammarAccess.getMathExpAccess().getNameAssignment_1(), "rule__MathExp__NameAssignment_1");
			builder.put(grammarAccess.getMathExpAccess().getExpAssignment_3(), "rule__MathExp__ExpAssignment_3");
			builder.put(grammarAccess.getExp1Access().getRightAssignment_1_0_2(), "rule__Exp1__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExp1Access().getRightAssignment_1_1_2(), "rule__Exp1__RightAssignment_1_1_2");
			builder.put(grammarAccess.getExp2Access().getRightAssignment_1_0_2(), "rule__Exp2__RightAssignment_1_0_2");
			builder.put(grammarAccess.getExp2Access().getRightAssignment_1_1_2(), "rule__Exp2__RightAssignment_1_1_2");
			builder.put(grammarAccess.getParenthesisAccess().getExpAssignment_1(), "rule__Parenthesis__ExpAssignment_1");
			builder.put(grammarAccess.getNumberAccess().getValueAssignment(), "rule__Number__ValueAssignment");
			builder.put(grammarAccess.getLetAccess().getNameAssignment_1(), "rule__Let__NameAssignment_1");
			builder.put(grammarAccess.getLetAccess().getValAssignment_3(), "rule__Let__ValAssignment_3");
			builder.put(grammarAccess.getLetAccess().getExpAssignment_5(), "rule__Let__ExpAssignment_5");
			builder.put(grammarAccess.getVariableUseAccess().getRefAssignment(), "rule__VariableUse__RefAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private MathGrammarAccess grammarAccess;

	@Override
	protected InternalMathParser createParser() {
		InternalMathParser result = new InternalMathParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MathGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MathGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
